name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -o ToPack
    - name: Move LICENSE.md
      run: cp LICENSE.md ToPack\
    - name: Move README.md
      run: cp README.md ToPack\
    - name: ZIP Pack
      run: Compress-Archive -Path ToPack\ -DestinationPath TR.caMonPageMod.HoanDisp.DevLatest.zip
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: TR.caMonPageMod.HoanDisp.DevLatest.zip
        path: TR.caMonPageMod.HoanDisp.DevLatest.zip
